name: hello-world

on:
  push:
    branches:
      - main
      - "candidate-*"
    paths:
      - "**"
      - "!folder/*"

jobs:
  my-job:
    runs-on: ubuntu-latest # this can also be windows or mac
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: make ramdisk
        run: |
          sudo mkdir -p /tmp/ramdisk
          sudo mount -t tmpfs tmpfs /tmp/ramdisk
      - name: Checkout
        uses: actions/checkout@v2
      - name: write to ramdisk
        run: |
          python3 write.py
