name: trigger-on-demand

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      name:
        description: 'Your name goes here'
        type: string
        required: true

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          # echo "Log level: $LEVEL"
          # echo "Tags: $TAGS"
          # echo "Environment: $NAME"
          export var_true=abcd
          export NON_EXISTING_VAR=false
          echo "branch_name=${GITHUB_REF/refs\/heads\//}" >> $GITHUB_OUTPUT
          echo "with_or=${{ NON_EXISTING_VAR || var_true }})" >> $GITHUB_OUTPUT
      - run: |
          echo "pi-${{ steps.vars.outputs.branch_name }}"
          echo "pi-${{ steps.vars.outputs.with_or }}"