name: trigger-on-demand

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      name:
        description: 'Your name goes here'
        type: string
        required: true

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $NAME"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          NAME: ${{ inputs.name }}
      - run: |
          echo "Hello World!" >> hello-world.txt
          echo "Hello World 2!" >> hello-world2.txt
      - uses: actions/upload-artifact@v3
        with:
          name: hello-world
          path: hello-world*.txt
