# Events List are listed here:
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
# 

name: trigger-on-event

on:
  pull_request:
    types: [opened, reopened]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
